# Generated by Django 5.1.7 on 2025-05-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'Analyses'},
        ),
    ]
